[package]
name = "sniperforge"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "sniperforge"
path = "src/main.rs"

[lib]
name = "sniperforge"
path = "src/lib.rs"

[dependencies]
# Async runtime
tokio = { version = "1.0", features = ["full"] }
tokio-tungstenite = "0.21"
futures-util = "0.3"
futures = "0.3"

# Solana
solana-sdk = "1.18"
solana-client = "1.18"
solana-account-decoder = "1.18"
solana-transaction-status = "1.18"

# Serde for serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"

# Web3 and crypto
anchor-client = "0.29"
anchor-lang = "0.29"
base64 = "0.21"
bs58 = "0.5"

# HTTP client
reqwest = { version = "0.11", features = ["json"] }

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"

# CLI and console
clap = { version = "4.0", features = ["derive"] }
console = "0.15"
colored = "2.0"
crossterm = "0.27"

# Utilities
anyhow = "1.0"
thiserror = "1.0"
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }

# Configuration
config = "0.14"

# Metrics and monitoring
metrics = "0.21"
metrics-exporter-prometheus = "0.12"
sysinfo = "0.30"

# Random number generation
rand = "0.8"

[dev-dependencies]
assert_matches = "1.5"
mockall = "0.12"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[profile.dev]
opt-level = 0
debug = true
