[package]
name = "sniperforge"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "sniperforge"
path = "src/main.rs"

[lib]
name = "sniperforge"
path = "src/lib.rs"

[dependencies]
# Async runtime - features mínimas pero funcionales
tokio = { version = "1.0", default-features = false, features = ["rt-multi-thread", "macros", "net", "time", "io-util"] }
tokio-tungstenite = { version = "0.27.0", default-features = false, features = ["connect", "rustls-tls-webpki-roots"] }
futures-util = { version = "0.3", default-features = false, features = ["std"] }
futures = { version = "0.3", default-features = false, features = ["std"] }

# Solana (minimal features for faster compilation)
solana-sdk = { version = "2.2.1", default-features = false, features = [] }
solana-client = { version = "2.2.1", default-features = false, features = [] }
solana-account-decoder = { version = "2.2.1", default-features = false, features = [] }
solana-transaction-status = { version = "2.2.1", default-features = false, features = [] }

# Serde for serialization - minimal pero funcional
serde = { version = "1.0", default-features = false, features = ["derive", "std"] }
serde_json = { version = "1.0", default-features = false, features = ["std"] }
toml = { version = "0.8", default-features = false, features = ["display"] }
dotenv = "0.15"
bincode = { version = "1.3", default-features = false }

# Web3 and crypto - minimal features
anchor-client = { version = "0.31.1", default-features = false }
anchor-lang = { version = "0.31.1", default-features = false }
base64 = { version = "0.22.1", default-features = false }
bs58 = { version = "0.5", default-features = false }

# HTTP client ultra-optimizado
reqwest = { version = "0.12.20", default-features = false, features = ["json", "rustls-tls"] }
url = "2.4"

# TLS/SSL support
rustls = { version = "0.23", features = ["ring"] }

# OpenSSL precompilado - descomenta para usar binarios precompilados
openssl = { version = "0.10", features = ["vendored"] }
openssl-sys = { version = "0.9", features = ["vendored"] }

# Random number generation for pool detection
rand = "0.8"

# Logging ultra-minimal pero funcional
tracing = { version = "0.1", default-features = false, features = ["std"] }
tracing-subscriber = { version = "0.3.19", default-features = false, features = ["env-filter", "std"] }
tracing-appender = { version = "0.2", default-features = false }

# CLI ultra-minimal pero con features necesarias para Windows
clap = { version = "4.0", default-features = false, features = ["derive", "std"] }
console = { version = "0.15", default-features = false }
colored = { version = "3.0.0", default-features = false }
crossterm = { version = "0.29.0", default-features = false, features = ["windows"] }

# Utilities
anyhow = "1.0"
thiserror = "1.0"
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }

# Configuration
config = "0.15.11"

# Metrics and monitoring
metrics = "0.24.2"
metrics-exporter-prometheus = "0.17.0"
sysinfo = "0.35.2"

[dev-dependencies]
assert_matches = "1.5"
mockall = "0.13.1"

[profile.dev]
opt-level = 0
debug = true
incremental = true
codegen-units = 256

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

# Force no OpenSSL dependencies
[features]
default = []
native-tls = []
