[package]
name = "sniperforge"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "request_devnet_airdrop"
path = "request_devnet_airdrop.rs"

[[bin]]
name = "test_devnet_tokens"
path = "test_devnet_tokens.rs"

[[bin]]
name = "create_test_wallet"
path = "create_test_wallet.rs"

[[bin]]
name = "sniperforge"
path = "src/main.rs"

[[bin]]
name = "verify_tokens"
path = "src/verify_tokens.rs"

[[bin]]
name = "test_all_rpc_methods"
path = "test_all_rpc_methods.rs"

[[bin]]
name = "get_wallet_address"
path = "get_wallet_address.rs"

[[bin]]
name = "test_orca_devnet_real"
path = "test_orca_devnet_real.rs"

[[bin]]
name = "test_orca_devnet_simple"
path = "test_orca_devnet_simple.rs"

[[bin]]
name = "test_simple_transfer"
path = "test_simple_transfer.rs"

[[bin]]
name = "test_real_trading"
path = "test_real_trading.rs"

[[bin]]
name = "test_real_execution"
path = "test_real_execution.rs"

[[bin]]
name = "test_sol_swap_real"
path = "test_sol_swap_real.rs"

[[bin]]
name = "test_real_swap_configured"
path = "test_real_swap_configured.rs"

[[bin]]
name = "test_jupiter_fixed"
path = "test_jupiter_fixed.rs"

[[bin]]
name = "test_sol_to_usdc_devnet"
path = "test_sol_to_usdc_devnet.rs"

[[bin]]
name = "find_working_routes"
path = "find_working_routes.rs"

[[bin]]
name = "test_json_config_trading"
path = "test_json_config_trading.rs"

[[bin]]
name = "verify_devnet_tokens"
path = "verify_devnet_tokens.rs"

[[bin]]
name = "find_real_devnet_tokens"
path = "find_real_devnet_tokens.rs"

[[bin]]
name = "create_devnet_tokens_automated"
path = "create_devnet_tokens_automated.rs"

[[bin]]
name = "test_automated_tokens"
path = "test_automated_tokens.rs"

[[bin]]
name = "test_devnet_functionality"
path = "test_devnet_functionality.rs"

[[bin]]
name = "test_arbitrage_devnet"
path = "test_arbitrage_devnet.rs"

[[bin]]
name = "test_arbitrage_devnet_simple"
path = "test_arbitrage_devnet_simple.rs"

[[bin]]
name = "test_arbitrage_status"
path = "test_arbitrage_status.rs"

[[bin]]
name = "test_arbitrage_quick"
path = "test_arbitrage_quick.rs"

[[bin]]
name = "test_arbitrage_bot_devnet"
path = "test_arbitrage_bot_devnet.rs"

[[bin]]
name = "test_arbitrage_devnet_new"
path = "test_arbitrage_devnet_new.rs"

[[bin]]
name = "discover_devnet_tokens"
path = "discover_devnet_tokens.rs"

[[bin]]
name = "test_arbitrage_real_devnet"
path = "test_arbitrage_real_devnet.rs"

[[bin]]
name = "test_arbitrage_production_devnet"
path = "test_arbitrage_production_devnet.rs"

[[bin]]
name = "test_arbitrage_real_profits"
path = "test_arbitrage_real_profits.rs"

[[bin]]
name = "test_arbitrage_execution_ready"
path = "test_arbitrage_execution_ready.rs"

[[bin]]
name = "test_real_arbitrage_devnet"
path = "test_real_arbitrage_devnet.rs"

[[bin]]
name = "test_enhanced_arbitrage_monitor"
path = "test_enhanced_arbitrage_monitor.rs"

[[bin]]
name = "qa_runner"
path = "tests/qa_runner.rs"

[[bin]]
name = "test_sol_wrap_unwrap"
path = "test_sol_wrap_unwrap.rs"

[[bin]]
name = "test_custom_tokens_swap"
path = "test_custom_tokens_swap.rs"

[[bin]]
name = "test_custom_tokens_verify"
path = "test_custom_tokens_verify.rs"

[[bin]]
name = "discover_jupiter_tokens"
path = "discover_jupiter_tokens.rs"

[[bin]]
name = "test_orca_direct_amm"
path = "test_orca_direct_amm.rs"

[[bin]]
name = "test_spl_token_swap"
path = "test_spl_token_swap.rs"

[[bin]]
name = "test_real_amm_arbitrage"
path = "test_real_amm_arbitrage.rs"

[[bin]]
name = "test_real_data_arbitrage"
path = "test_real_data_arbitrage.rs"

[[bin]]
name = "test_market_data_arbitrage"
path = "test_market_data_arbitrage.rs"

[[bin]]
name = "test_realtime_arbitrage_monitor"
path = "test_realtime_arbitrage_monitor.rs"

[[bin]]
name = "check_devnet_balance"
path = "check_devnet_balance.rs"

[[bin]]
name = "test_simple_arbitrage_real"
path = "test_simple_arbitrage_real.rs"

[[bin]]
name = "test_arbitrage_real_jupiter"
path = "test_arbitrage_real_jupiter.rs"

[[bin]]
name = "test_arbitrage_cross_dex"
path = "test_arbitrage_cross_dex.rs"

[lib]
name = "sniperforge"
path = "src/lib.rs"

[dependencies]
# Async runtime - features mínimas pero funcionales
tokio = { version = "1.0", default-features = false, features = ["rt-multi-thread", "macros", "net", "time", "io-util"] }
tokio-tungstenite = { version = "0.27.0", default-features = false, features = ["connect", "rustls-tls-webpki-roots"] }
futures-util = { version = "0.3", default-features = false, features = ["std"] }
futures = { version = "0.3", default-features = false, features = ["std"] }

# Solana (exact versions known to work together for mainnet trading)
solana-sdk = { version = "=2.2.1", default-features = false, features = ["full"] }
solana-client = { version = "=2.2.1", default-features = false, features = [] }
solana-account-decoder = { version = "=2.2.1", default-features = false, features = [] }
solana-transaction-status = { version = "=2.2.1", default-features = false, features = [] }
spl-token = { version = "=6.0.0", default-features = false }
spl-associated-token-account = { version = "=4.0.0", default-features = false }

# Serde for serialization - minimal pero funcional
serde = { version = "1.0", default-features = false, features = ["derive", "std"] }
serde_json = { version = "1.0", default-features = false, features = ["std"] }
toml = { version = "0.8", default-features = false, features = ["display"] }
dotenv = "0.15"
bincode = { version = "1.3", default-features = false }

# Logging and error handling
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }

# Web3 and crypto - compatible versions with Solana 2.2.1
# anchor-client = { version = "0.30.1", default-features = false }
# anchor-lang = { version = "0.30.1", default-features = false }

# Orca Whirlpool SDK
orca_whirlpools = { version = "3.1.0", default-features = false }
base64 = { version = "0.22.1", default-features = false }
bs58 = { version = "0.5", default-features = false }
bip39 = { version = "2.0", default-features = false, features = ["std"] }
hex = { version = "0.4", default-features = false }


# TLS/SSL support
rustls = { version = "0.23", features = ["ring"] }

# OpenSSL precompilado - descomenta para usar binarios precompilados
openssl = { version = "0.10", features = ["vendored"] }
openssl-sys = { version = "0.9", features = ["vendored"] }

# Random number generation
rand = "0.8"

# Additional dependencies for trading engine
async-trait = "0.1"
uuid = { version = "1.0", features = ["v4", "serde"] }

# Logging ultra-minimal pero funcional - already defined above
# tracing = { version = "0.1", default-features = false, features = ["std"] }
# tracing-subscriber = { version = "0.3.19", default-features = false, features = ["env-filter", "std"] }
tracing-appender = { version = "0.2", default-features = false }

# CLI ultra-minimal pero con features necesarias para Windows
clap = { version = "4.0", default-features = false, features = ["derive", "std"] }
console = { version = "0.15", default-features = false }
colored = { version = "3.0.0", default-features = false }
crossterm = { version = "0.29.0", default-features = false, features = ["windows"] }

# Utilities - already defined above
# anyhow = "1.0"
thiserror = "1.0"
# chrono = { version = "0.4", features = ["serde"] } # already defined above

# Configuration
config = "0.15.11"

# Machine Learning & Data Science (Phase 6B)
candle-core = "0.8.0"
candle-nn = "0.8.0"
ndarray = "0.16.1"
ndarray-stats = "0.6.0"
linfa = "0.7.0"
linfa-clustering = "0.7.0"
polars = { version = "0.45.1", features = ["lazy", "temporal", "strings"] }
plotters = "0.3.7"
smartcore = "0.3.2"

# Metrics and monitoring
metrics = "0.24.2"
metrics-exporter-prometheus = "0.17.0"
sysinfo = "0.35.2"

# Temporary files for ML model storage
tempfile = "3.8"
ureq = { version = "3.0.12", features = ["json"] }

[dev-dependencies]
assert_matches = "1.5"
mockall = "0.13.1"

[profile.dev]
opt-level = 0
debug = true
incremental = true
codegen-units = 256

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

# Force no OpenSSL dependencies
[features]
default = []
native-tls = []
