[platform]
name = "SniperForge"
version = "0.1.0"
max_concurrent_bots = 3
resource_allocation_strategy = "priority_based"
event_bus_buffer_size = 5000

# HYBRID TRADING MODE - Sprint 1.5
[trading]
mode = "hybrid"  # devnet_real + mainnet_paper
devnet_real_trading = true
mainnet_paper_trading = true

[network]
# DEVNET CONFIGURATION - SAFE FOR TESTING
environment = "devnet"

# Devnet endpoints (for testing) - Updated June 28, 2025
devnet_primary_rpc = "https://api.devnet.solana.com"
devnet_backup_rpc = [
    # Official Solana Labs devnet endpoint - Most reliable for testing
    "https://api.devnet.solana.com",
    
    # Note: The following endpoints require API keys:
    # - "https://devnet.helius-rpc.com" (401 Unauthorized - API key required)
    # - "https://rpc-devnet.hellomoon.io" (400 Bad Request - API key required)
    
    # For testing purposes, the official endpoint is sufficient
    # For production devnet testing, consider getting free API keys from:
    # - Helius (devnet access often free)
    # - Alchemy, QuickNode, etc.
]
devnet_websocket_url = "wss://api.devnet.solana.com"

# Connection settings
connection_timeout_ms = 10000
request_timeout_ms = 15000
retry_attempts = 3
retry_delay_ms = 1000

[shared_services]
rpc_pool_size = 10
wallet_isolation = true
data_feed_aggregation = true
monitoring_enabled = true

[security]
# Wallet configuration (NEVER commit real private keys)
wallet_encryption_enabled = true
key_derivation_iterations = 100000
session_timeout_minutes = 30

# Wallet configuration - Sprint 1.5
[wallets]
auto_generate = true
auto_airdrop_devnet = true
devnet_airdrop_amount = 5.0  # 5 SOL for testing

# DevNet wallet (real keypair for testing)
[wallets.devnet]
enabled = true
real_trading = true
paper_trading = false
initial_balance_sol = 5.0
max_trade_amount_sol = 1.0

# MainNet wallet (virtual/paper trading only)
[wallets.mainnet]
enabled = true
real_trading = false
paper_trading = true
virtual_balance_sol = 100.0  # Virtual money for simulation
max_trade_amount_sol = 10.0

[logging]
level = "info"
file_enabled = true
console_enabled = true
max_file_size_mb = 50
max_files = 5

# Bot-specific configurations
[bots.lp_sniper]
enabled = true
priority = "high"
resource_allocation = { cpu = "30%", memory = "512MB" }

[bots.lp_sniper.detection]
target_dexs = ["raydium"]
min_liquidity_usd = 1000    # Lower threshold for testing
max_response_time_ms = 500  # More relaxed for devnet
pool_creation_buffer_blocks = 5

[bots.lp_sniper.risk]
max_position_size_usd = 100   # Much lower for testing
max_slippage_percent = 5.0
stop_loss_percent = -15.0
take_profit_percent = 25.0

[bots.copy_trading]
enabled = false
priority = "medium"
resource_allocation = { cpu = "15%", memory = "256MB" }

[bots.arbitrage]
enabled = false
priority = "high"
resource_allocation = { cpu = "20%", memory = "256MB" }

[bots.mev]
enabled = false
priority = "critical"
resource_allocation = { cpu = "25%", memory = "512MB" }

# Development settings
[development]
simulate_trades = false  # ENABLE REAL TRADES IN DEVNET
use_devnet = true       # EXPLICITLY USE DEVNET
verbose_logging = true
enable_debug_mode = true

# Performance settings
[performance]
target_latency_ms = 100     # More relaxed for testing
max_memory_usage_mb = 1024  # Lower memory usage
gc_interval_seconds = 30
metrics_collection_interval_ms = 2000
