# SniperForge Mainnet Configuration
# Paper Trading with Real Mainnet Data
#
# TIME UNITS GUIDE:
# - _ms suffix: MILLISECONDS (high-frequency operations, 1000ms = 1 second)
# - _seconds suffix: SECONDS (monitoring durations, API calls)
# - _minutes suffix: MINUTES (session timeouts, 60 minutes = 1 hour)
# - _hours suffix: HOURS (long-term limits, 24 hours = 1 day)
# Always check the suffix and comments for the exact unit used.

[platform]
name = "SniperForge"
version = "0.1.0"
max_concurrent_bots = 3
resource_allocation_strategy = "priority_based"
event_bus_buffer_size = 5000

[network]
# MAINNET CONFIGURATION - REAL MONEY AT RISK
environment = "mainnet"

# Mainnet endpoints (for production - REAL MONEY OPERATIONS)
mainnet_primary_rpc = "https://api.mainnet-beta.solana.com"
mainnet_backup_rpc = [
    "https://solana-api.projectserum.com",
    "https://rpc.ankr.com/solana"
]
mainnet_websocket_url = "wss://api.mainnet-beta.solana.com"

# Connection settings
connection_timeout_ms = 3000  # Faster timeout for mainnet
request_timeout_ms = 8000

[shared_services]
rpc_pool_size = 20
wallet_isolation = true
data_feed_aggregation = true
monitoring_enabled = true

[security]
# Wallet configuration (NEVER commit real private keys)
wallet_encryption_enabled = true
key_derivation_iterations = 100000
session_timeout_minutes = 30

[logging]
level = "info"
file_path = "logs/sniperforge.log"
max_file_size_mb = 100
max_files = 10
console_output = true

[bots]
lp_sniper = { enabled = false }      # DISABLED for safety
copy_trading = { enabled = false }   # DISABLED for safety
arbitrage = { enabled = false }      # DISABLED for safety
mev = { enabled = false }           # DISABLED for safety

[development]
enable_hot_reload = false           # Production mode
mock_mode = false                  # Real trading mode
debug_logging = false              # Reduced logging for performance

[performance]
# Enhanced performance settings for mainnet
max_memory_usage_mb = 1024
gc_interval_seconds = 300
thread_pool_size = 8
batch_processing_enabled = true

[jupiter]
# Official Jupiter API for mainnet
base_url = "https://quote-api.jup.ag"
timeout_ms = 5000
max_retries = 3
cache_ttl_ms = 100  # Very short cache for real-time data

[syndica]
# Syndica mainnet WebSocket
endpoint = "wss://solana-mainnet.api.syndica.io"
# You need a real Syndica token for mainnet
access_token = "${SYNDICA_MAINNET_TOKEN}"
reconnect_attempts = 5
ping_interval_sec = 30

[paper_trading]
# Paper trading configuration
initial_sol_balance = 10.0
initial_usdc_balance = 2000.0
simulated_fee_bps = 30        # 0.3% realistic fees
simulated_slippage_percent = 0.1  # 0.1% slippage
execution_latency_ms = 150    # Realistic execution latency

[safety]
# Ultra-safe settings for mainnet
# Time units: milliseconds (ms) for high-frequency operations
max_price_age_ms = 50         # Only accept prices < 50ms old (MILLISECONDS)
min_price_sources = 2         # Require at least 2 price sources
price_tolerance_percent = 0.5 # Max 0.5% difference between sources
disable_cache_for_trading = true  # Never use cache for trading decisions

[monitoring]
# Performance monitoring
log_all_trades = true
log_price_sources = true
log_latency = true
save_trade_history = true

[risk_management]
# Additional safety for mainnet
max_trade_size_sol = 1.0      # Max 1 SOL per trade in paper mode
max_daily_trades = 100        # Max 100 trades per day
enable_circuit_breaker = true # Stop trading on consecutive losses
max_consecutive_losses = 5    # Stop after 5 consecutive losses

[pool_detection]
# Pool detection parameters - easily adjustable without recompiling
# Time units clearly specified for each parameter
min_liquidity_usd = 1000.0    # Minimum pool liquidity (lower for testing)
max_price_impact_1k = 15.0    # Maximum price impact for 1K trade (higher for testing)
min_risk_score = 0.1          # Minimum risk score (0.1 = 10%, lower for testing)
monitoring_interval_ms = 2000 # How often to scan for pools (MILLISECONDS - 2000ms = 2 seconds)
max_tracked_pools = 200       # Maximum pools to track simultaneously

# Opportunity detection thresholds
min_profit_threshold_usd = 5.0    # Minimum profit to consider (lower for testing)
min_confidence_score = 0.6        # Minimum confidence (60%, lower for testing)
max_execution_time_ms = 5000      # Maximum time to execute trade (MILLISECONDS - 5000ms = 5 seconds)
enable_new_pool_detection = true  # Enable event-based new pool detection
enable_websocket_triggers = true  # Use WebSocket events instead of polling

[trading_session]
# Default trading session parameters
# Time units: minutes for session-level timeouts and durations
default_max_capital = 1000.0      # Default max capital
default_max_trade = 100.0         # Default max single trade
default_daily_limit = 200.0       # Default daily loss limit
default_duration_minutes = 30     # Default session duration (MINUTES - 30min = 0.5 hours)
