# SniperForge Mainnet Configuration
# Paper Trading with Real Mainnet Data
#
# TIME UNITS GUIDE:
# - _ms suffix: MILLISECONDS (high-frequency operations, 1000ms = 1 second)
# - _seconds suffix: SECONDS (monitoring durations, API calls)
# - _minutes suffix: MINUTES (session timeouts, 60 minutes = 1 hour)
# - _hours suffix: HOURS (long-term limits, 24 hours = 1 day)
# Always check the suffix and comments for the exact unit used.

[platform]
name = "SniperForge"
version = "0.1.0"
max_concurrent_bots = 3
resource_allocation_strategy = "priority_based"
event_bus_buffer_size = 5000

[network]
# MAINNET CONFIGURATION - REAL MONEY AT RISK
environment = "mainnet"

# Mainnet endpoints (for production - REAL MONEY OPERATIONS)
# Updated June 28, 2025 - CRITICAL RPC RESILIENCE IMPROVEMENTS
# Multiple tiers of endpoints for maximum reliability
mainnet_primary_rpc = "https://api.mainnet-beta.solana.com"

# Tier 1: High-reliability public endpoints (working as of June 28, 2025)
mainnet_backup_rpc = [
    # Official Solana Labs endpoints - Most reliable
    "https://api.mainnet-beta.solana.com",
    
    # Major infrastructure providers that work without API keys
    "https://solana.publicnode.com",
    
    # Additional reliable providers (API key NOT required)
    # Note: Many RPC providers now require API keys for mainnet access
    # The following endpoints require registration/API keys:
    # - "https://rpc.ankr.com/solana" (403 Forbidden - API key required)
    # - "https://mainnet.helius-rpc.com" (401 Unauthorized - API key required) 
    # - "https://solana-mainnet.rpc.extrnode.com" (401 Unauthorized - API key required)
    # - DNS resolution failures: phantom.tech, blockdaemon.com, blastapi.io, etc.
    
    # For production use, consider:
    # 1. Getting API keys from major providers (Helius, Ankr, QuickNode)
    # 2. Running your own RPC node
    # 3. Using paid RPC services for better reliability
]

# Tier 2: Alternative data sources for pool detection
raydium_api_base = "https://api.raydium.io"
jupiter_api_base = "https://quote-api.jup.ag"
birdeye_api_base = "https://public-api.birdeye.so"
dexscreener_api_base = "https://api.dexscreener.com/latest/dex"
mainnet_websocket_url = "wss://api.mainnet-beta.solana.com"

# Connection settings - Optimized for mainnet resilience
connection_timeout_ms = 12000      # Increased for unreliable networks
request_timeout_ms = 20000         # Higher timeout for heavy operations
retry_attempts = 8                 # More retry attempts for resilience
retry_delay_ms = 2000              # Longer delay between retries
max_concurrent_requests = 15       # Limit concurrent requests to avoid rate limiting
rpc_rotation_strategy = "smart"    # smart, round_robin, health_based
health_check_interval_seconds = 30 # How often to check RPC health
circuit_breaker_threshold = 5      # Failures before marking RPC as down
circuit_breaker_reset_seconds = 120 # How long to wait before retrying failed RPC

[shared_services]
rpc_pool_size = 20
wallet_isolation = true
data_feed_aggregation = true
monitoring_enabled = true

[security]
# Wallet configuration (NEVER commit real private keys)
wallet_encryption_enabled = true
key_derivation_iterations = 100000
session_timeout_minutes = 30

[logging]
level = "info"
file_enabled = true
console_enabled = true
max_file_size_mb = 100
max_files = 10

[bots]
[bots.lp_sniper]
enabled = false
priority = "low"
resource_allocation = { cpu = "10%", memory = "50MB" }

[bots.copy_trading]
enabled = false
priority = "low"
resource_allocation = { cpu = "10%", memory = "50MB" }

[bots.arbitrage]
enabled = false
priority = "low"
resource_allocation = { cpu = "10%", memory = "50MB" }

[bots.mev]
enabled = false
priority = "low"
resource_allocation = { cpu = "10%", memory = "50MB" }

[development]
simulate_trades = false            # Real trading mode
use_devnet = false                 # Use mainnet
verbose_logging = false            # Reduced logging for performance
enable_debug_mode = false          # Production mode

[performance]
# Enhanced performance settings for mainnet
target_latency_ms = 50             # Target latency for mainnet
max_memory_usage_mb = 1024
gc_interval_seconds = 300
metrics_collection_interval_ms = 1000

[safety]
# Ultra-safe settings for mainnet
# Time units: milliseconds (ms) for high-frequency operations
max_price_age_ms = 50         # Only accept prices < 50ms old (MILLISECONDS)
min_price_sources = 2         # Require at least 2 price sources
price_tolerance_percent = 0.5 # Max 0.5% difference between sources
disable_cache_for_trading = true  # Never use cache for trading decisions

[monitoring]
# Performance monitoring
log_all_trades = true
log_price_sources = true
log_latency = true
save_trade_history = true

[risk_management]
# Additional safety for mainnet
max_trade_size_sol = 1.0      # Max 1 SOL per trade in paper mode
max_daily_trades = 100        # Max 100 trades per day
enable_circuit_breaker = true # Stop trading on consecutive losses
max_consecutive_losses = 5    # Stop after 5 consecutive losses

[pool_detection]
# Pool detection parameters - easily adjustable without recompiling
# Time units clearly specified for each parameter
min_liquidity_usd = 1000.0    # Minimum pool liquidity (lower for testing)
max_price_impact_1k = 15.0    # Maximum price impact for 1K trade (higher for testing)
min_risk_score = 0.1          # Minimum risk score (0.1 = 10%, lower for testing)
monitoring_interval_ms = 2000 # How often to scan for pools (MILLISECONDS - 2000ms = 2 seconds)
max_tracked_pools = 200       # Maximum pools to track simultaneously

# Opportunity detection thresholds
min_profit_threshold_usd = 5.0    # Minimum profit to consider (lower for testing)
min_confidence_score = 0.6        # Minimum confidence (60%, lower for testing)
max_execution_time_ms = 5000      # Maximum time to execute trade (MILLISECONDS - 5000ms = 5 seconds)
enable_new_pool_detection = true  # Enable event-based new pool detection
enable_websocket_triggers = true  # Use WebSocket events instead of polling

[trading_session]
# Default trading session parameters
# Time units: minutes for session-level timeouts and durations
default_max_capital = 1000.0      # Default max capital
default_max_trade = 100.0         # Default max single trade
default_daily_limit = 200.0       # Default daily loss limit
default_duration_minutes = 30     # Default session duration (MINUTES - 30min = 0.5 hours)
