[package]
name = "orca_devnet_test"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = "2.1.0"
solana-sdk = "2.1.0"

[[bin]]
name = "test_orca_devnet_simple"
path = "test_orca_devnet_simple.rs"
